---
name: test

on:
  push:
  workflow_dispatch:
  repository_dispatch:
  
jobs:
  information:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print debug
        uses: hmarr/debug-action@v2  
